/**
 * Render infrastructure/supervisord.conf from the canonical agent roster.
 * Companion to scripts/generate-compose.ts: same source of truth (agent
 * slots + display names), different output target.
 *
 * The output drives the packed-fleet Fly deployment (Dockerfile.fly), where
 * a single supervisord process spawns the axl-spoke + 60 agent processes
 * inside one Fly machine.
 *
 * Usage:
 *   npm run supervisor:generate
 *
 * Regenerate whenever agents/src/wallets.ts or display_names.ts change.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { displayNameFor } from "../agents/src/display_names.js";
import { type AgentRole, allAgentSlots } from "../agents/src/wallets.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "infrastructure/supervisord.conf");

const HEADER = `; Generated by scripts/generate-supervisor-conf.ts. Do not edit by hand -
; update the inputs (agents/src/wallets.ts, agents/src/display_names.ts) and
; rerun \`npm run supervisor:generate\`.
;
; This config drives the packed-fleet Fly deployment (Dockerfile.fly).
; supervisord runs the axl-spoke gossip hub + 60 agent processes inside
; one Fly machine. Stdout/stderr stream to the container's stdout so Fly
; captures them; no log rotation needed.
;
; Stagger: priorities 100 (spoke) -> 200 (traders) -> 300 (wolves) ->
; 400 (publishers) -> 500 (watcher) -> 600 (scenario), with startsecs=2.
; The full fleet boots over ~2 minutes.

[supervisord]
nodaemon=true
loglevel=info
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:axl-spoke]
command=/usr/local/bin/axl-hub -config /etc/axl/spoke.json
environment=AXL_CONFIG="/etc/axl/spoke.json",KEY_PATH="/data/private.pem"
priority=100
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
`;

const ROLE_PRIORITY: Record<AgentRole, number> = {
  trader: 200,
  wolf: 300,
  publisher: 400,
  watcher: 500,
  scenario: 600,
};

function agentBlock(agentId: string, role: AgentRole, displayName: string): string {
  return `
[program:agent-${agentId}]
command=node --enable-source-maps /app/dist/agent.js
directory=/app
environment=AGENT_ID="${agentId}",AGENT_ROLE="${role}",AGENT_DISPLAY_NAME="${displayName}"
priority=${ROLE_PRIORITY[role]}
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=15
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
`;
}

async function main(): Promise<void> {
  const slots = allAgentSlots();
  const blocks = slots.map((s) => agentBlock(s.agentId, s.role, displayNameFor(s.agentId)));
  const out = HEADER + blocks.join("");
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, out);
  console.log(`wrote ${OUT} (${slots.length} agent blocks + 1 spoke)`);
}

main().catch((err) => {
  console.error("fatal:", err);
  process.exit(1);
});
