/**
 * Render docker-compose.yml from the canonical agent roster in
 * agents/src/wallets.ts + display name registry. Run this whenever the role
 * counts or display names change; the generated file is committed.
 *
 * Usage:
 *   npm run compose:generate
 *
 * The output:
 *   - one service per agent (60 total), all building from agents/Dockerfile
 *   - one axl-spoke service (ghcr.io/immunity-protocol/axl-hub:latest)
 *   - external network `immunity-app_default` so agents reach the app's
 *     postgres at hostname `immunity_database`
 *
 * The generator does NOT inline secrets — every agent reads the same .env
 * file via docker compose's env_file.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allAgentSlots } from "../agents/src/wallets.js";
import { displayNameFor } from "../agents/src/display_names.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT  = path.join(ROOT, "docker-compose.yml");

const NETWORK_NAME = process.env.IMMUNITY_DEMO_NETWORK ?? "immunity-app_default";

const HEADER = `# Generated by scripts/generate-compose.ts. Do not edit by hand —
# update the inputs (agents/src/wallets.ts, agents/src/display_names.ts) and
# rerun \`npm run compose:generate\`.
#
# Network: joins the running app's docker network (default
# "immunity-app_default") so agents reach postgres at "immunity_database".

name: immunity-demo
`;

const AXL_BLOCK = `
  axl-spoke:
    image: ghcr.io/immunity-protocol/axl-hub:latest
    container_name: immunity-axl-spoke
    restart: unless-stopped
    environment:
      AXL_CONFIG: /etc/axl/spoke.json
      KEY_PATH: /data/private.pem
    volumes:
      - axl-data:/data
`;

const NETWORK_BLOCK = `
networks:
  default:
    name: ${NETWORK_NAME}
    external: true

volumes:
  axl-data: {}
`;

function agentBlock(agentId: string, role: string, displayName: string): string {
  const containerName = `immunity-demo-${agentId}`;
  return `
  ${agentId}:
    build:
      context: ./agents
      dockerfile: Dockerfile
    image: immunity-demo-agent:latest
    container_name: ${containerName}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      AGENT_ID: ${agentId}
      AGENT_ROLE: ${role}
      AGENT_DISPLAY_NAME: ${displayName}
    depends_on:
      - axl-spoke
`;
}

async function main(): Promise<void> {
  const slots = allAgentSlots();
  const blocks = ["services:", AXL_BLOCK];
  for (const slot of slots) {
    blocks.push(agentBlock(slot.agentId, slot.role, displayNameFor(slot.agentId)));
  }
  blocks.push(NETWORK_BLOCK);
  const content = HEADER + blocks.join("");
  await fs.writeFile(OUT, content);
  console.log(`wrote ${OUT}  (${slots.length} agents + axl-spoke)`);
}

main().catch((err) => {
  console.error("fatal:", err);
  process.exit(1);
});
