/**
 * Render infrastructure/supervisord.conf + per-agent AXL spoke configs from
 * the canonical agent roster.
 *
 * Each agent gets:
 *   - its own AXL spoke process (api on a unique port, own ed25519 key)
 *   - its own agent program block referencing AXL_URL on that port
 *
 * Why 60 spokes (one per agent) and not a single shared one: AXL routes
 * `/send` by destination peer-id. With a shared spoke, all 60 agents
 * advertise the same peer-id; wolf DMs to "trader-29" loopback to the
 * shared `/recv` queue and never reach the targeted trader. Each-agent-
 * own-spoke gives every agent a distinct ed25519 identity, so /send to
 * `trader-29.peer_id` actually delivers to trader-29's spoke and is read
 * by trader-29's drainInbox.
 *
 * This generator owns three outputs:
 *   1. infrastructure/supervisord.conf — 60 spoke + 60 agent program blocks
 *   2. infrastructure/axl-spokes/spoke-<agent_id>.json — per-spoke configs
 *   3. infrastructure/spoke-roster.txt — agent_id list for the keygen script
 *
 * Companion to scripts/generate-compose.ts (local docker-compose) and
 * infrastructure/generate-keys.sh (creates the 60 ed25519 keys at boot).
 *
 * Usage:
 *   npm run supervisor:generate
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { displayNameFor } from "../agents/src/display_names.js";
import { type AgentRole, allAgentSlots } from "../agents/src/wallets.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SUPERVISORD_OUT = path.join(ROOT, "infrastructure/supervisord.conf");
const SPOKE_DIR = path.join(ROOT, "infrastructure/axl-spokes");
const ROSTER_OUT = path.join(ROOT, "infrastructure/spoke-roster.txt");

const HEADER = `; Generated by scripts/generate-supervisor-conf.ts. Do not edit by hand -
; update the inputs (agents/src/wallets.ts, agents/src/display_names.ts) and
; rerun \`npm run supervisor:generate\`.
;
; Drives the packed-fleet Fly deployment (Dockerfile.fly). One supervisord
; process spawns 60 axl-spoke daemons (one per agent, distinct peer-id) +
; 60 agent processes inside one Fly machine.
;
; Boot order via priorities: 100 (spokes) -> 200 (traders) -> 300 (wolves)
; -> 400 (publishers) -> 600 (scenario), startsecs=2.
; Spoke key-gen happens once at container entrypoint via /usr/local/bin/
; generate-keys.sh which reads /etc/axl/spoke-roster.txt.

[supervisord]
nodaemon=true
loglevel=info
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
`;

const ROLE_PRIORITY: Record<AgentRole, number> = {
  trader: 200,
  wolf: 300,
  publisher: 400,
  scenario: 600,
};

// Stagger agent startup so 60 simultaneous boots don't blow past the 0G
// public RPC's 50 req/s cap. 2000ms × ordinal ⇒ full fleet finishes
// booting in ~2 minutes after the spokes are up. The first live boot
// (with 500ms stagger) saw a thundering-herd pile-up at the rate limiter
// that left ~20 agents stuck in retry loops; 2s gives plenty of room.
const STARTUP_STAGGER_MS = 2000;

// Spokes also stagger but more tightly — they only do peer-handshake
// work, not on-chain RPC, so they don't pressure the rate limiter.
const SPOKE_STAGGER_MS = 250;

// Each spoke binds an api port on 127.0.0.1; the agent connects to its
// own spoke at this offset. Range: 9002..9061 for 60 agents.
const SPOKE_API_PORT_BASE = 9002;

function spokeName(agentId: string): string {
  return `axl-spoke-${agentId}`;
}

function spokeConfigPath(agentId: string): string {
  return `/etc/axl/spokes/spoke-${agentId}.json`;
}

function spokeKeyPath(agentId: string): string {
  return `/data/spoke-${agentId}.pem`;
}

function spokePort(ordinal: number): number {
  return SPOKE_API_PORT_BASE + ordinal;
}

function spokeBlock(agentId: string, ordinal: number): string {
  const startupDelay = ordinal * SPOKE_STAGGER_MS;
  return `
[program:${spokeName(agentId)}]
command=/usr/local/bin/axl-hub -config ${spokeConfigPath(agentId)}
environment=AXL_CONFIG="${spokeConfigPath(agentId)}",KEY_PATH="${spokeKeyPath(agentId)}",STARTUP_DELAY_MS="${startupDelay}"
priority=100
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
`;
}

function agentBlock(
  agentId: string,
  role: AgentRole,
  displayName: string,
  ordinal: number,
): string {
  const delayMs = ordinal * STARTUP_STAGGER_MS;
  const port = spokePort(ordinal);
  return `
[program:agent-${agentId}]
command=node --enable-source-maps /app/dist/agent.js
directory=/app
environment=AGENT_ID="${agentId}",AGENT_ROLE="${role}",AGENT_DISPLAY_NAME="${displayName}",STARTUP_DELAY_MS="${delayMs}",AXL_URL="http://localhost:${port}"
priority=${ROLE_PRIORITY[role]}
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=15
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
`;
}

function spokeConfig(agentId: string, ordinal: number): string {
  return JSON.stringify(
    {
      PrivateKeyPath: spokeKeyPath(agentId),
      Peers: [
        "tls://hub-can.immunity-protocol.com:9001",
        "tls://hub-usa.immunity-protocol.com:9001",
      ],
      Listen: [],
      bridge_addr: "0.0.0.0",
      api_port: spokePort(ordinal),
    },
    null,
    2,
  ) + "\n";
}

async function main(): Promise<void> {
  const slots = allAgentSlots();
  const ordinalById = new Map(slots.map((s, i) => [s.agentId, i] as const));

  // 1. Per-spoke configs.
  await fs.mkdir(SPOKE_DIR, { recursive: true });
  for (const slot of slots) {
    const ord = ordinalById.get(slot.agentId)!;
    const out = path.join(SPOKE_DIR, `spoke-${slot.agentId}.json`);
    await fs.writeFile(out, spokeConfig(slot.agentId, ord));
  }

  // 2. Roster file consumed by the keygen entrypoint.
  await fs.writeFile(ROSTER_OUT, slots.map((s) => s.agentId).join("\n") + "\n");

  // 3. supervisord.conf with 60 spoke blocks then 60 agent blocks.
  const blocks: string[] = [];
  for (const slot of slots) {
    const ord = ordinalById.get(slot.agentId)!;
    blocks.push(spokeBlock(slot.agentId, ord));
  }
  for (const slot of slots) {
    const ord = ordinalById.get(slot.agentId)!;
    blocks.push(agentBlock(slot.agentId, slot.role, displayNameFor(slot.agentId), ord));
  }
  const out = HEADER + blocks.join("");
  await fs.mkdir(path.dirname(SUPERVISORD_OUT), { recursive: true });
  await fs.writeFile(SUPERVISORD_OUT, out);

  console.log(
    `wrote ${SUPERVISORD_OUT} (${slots.length} spokes + ${slots.length} agents),` +
      ` ${slots.length} spoke configs in ${SPOKE_DIR}, roster at ${ROSTER_OUT}`,
  );
}

main().catch((err) => {
  console.error("fatal:", err);
  process.exit(1);
});
